## 파이썬 기본 코드작성
* python base 문법 
* ctrl + enter : 해당 셀만 실행 
* shift + enter : 해당 셀을 실행하고 , 커서를 아래로 이동, 하위 셀이 없으면 추가
* alt + enter : 해당 셀을 실행하고, 무조건 하위 셀을 추가

In [2]:
my_list = [10,20,30]
my_list

[10, 20, 30]

In [3]:
fruits = ['apple','banana','cherry','kiwi','mango']
#과일이름에 a가 포함된 과일 리스트 만들기
a_list = []
for fruit in fruits:
    if "a" in fruit:
        a_list.append(fruit)

print(a_list)        

['apple', 'banana', 'mango']


In [4]:
#newlist = [expression for item in iterable if condition == True]
a_list2 = [fruit for fruit in fruits if "a" in fruit]
print(a_list2)

['apple', 'banana', 'mango']


In [5]:
#default parameter value
def mimus(a,b=10):
    return a - b

In [7]:
mimus(3)

-7

In [9]:
mimus(10,3)

7

In [12]:
#SyntaxError: non-default argument follows default argument
# def minus2(a=10,b):
#     return a - b

In [13]:
my_value = 12494949
def my_format(value):
    return f'{value:,}'

In [15]:
my_format(my_value)

'12,494,949'

In [22]:
# 람다함수, 익명함수
my_format2 = lambda val : f'{val:,}'

In [23]:
my_format2(my_value)

'12,494,949'

In [25]:
dt_list = ['정당','선거구','당선횟수']
dd_list = ['민주당','서울은평구','초선']

zip(dt_list,dd_list)

In [27]:
for data in zip(dt_list,dd_list):
    print(data)

('정당', '민주당')
('선거구', '서울은평구')
('당선횟수', '초선')


In [28]:
dict(zip(dt_list,dd_list))

{'정당': '민주당', '선거구': '서울은평구', '당선횟수': '초선'}

In [30]:
from datetime import date

today = date.today()
print(today)
print(today.year)
print(today.month)
print(today.day)

2021-11-18
2021
11
18


In [32]:
birth_1 = date(1960,2,5)
birth_2 = date(1960,12,1)
print(birth_1, birth_2)

1960-02-05 1960-12-01


In [34]:
#True - 1, False - 0
(2,5) < (12,1)

True

In [38]:
(today.month, today.day) < (birth_1.month, birth_1.day)  #0

False

In [40]:
(today.month, today.day) < (birth_2.month, birth_2.day) #1

True

In [42]:
age = today.year - birth_1.year - ((today.month, today.day) < (birth_1.month, birth_1.day))
print(age)

61


In [44]:
age = today.year - birth_2.year - ((today.month, today.day) < (birth_2.month, birth_2.day))
print(age)

60


In [45]:
import numpy as np 

In [46]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [48]:
print(arr.dtype)
arr.shape

int32


(4,)

In [50]:
arr2d =np.array( [[1,2,3,4],
         [5,6,7,8],
         [9,10,11,12],
         [13,14,15,16]
        ])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
arr2d[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
arr2d[1,:]

array([5, 6, 7, 8])

In [59]:
arr2d[:,1]

array([ 2,  6, 10, 14])

In [62]:
arr2d[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [63]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
arr2d.sum(axis=0)

array([28, 32, 36, 40])

In [67]:
arr2d.sum(axis=1)

array([10, 26, 42, 58])