In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[5:8] = 12

In [8]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [9]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [36]:
arr2d = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

In [38]:
arr = np.arange(1,17)

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [40]:
arr2d = arr.reshape(4,4)

In [41]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
arr2d[3,2]

15

In [48]:
arr2d[2,:]

array([ 9, 10, 11, 12])

In [43]:
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
arr2d[:,3]

array([ 4,  8, 12, 16])

In [45]:
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [49]:
arr2d[:2,1:3] = 0

In [50]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [53]:
names = np.array(["Charles","Soyul","Hayoung","Charles","Hayoung","Soyul","Soyul"])
data = np.random.randn(7,4)

In [52]:
names

array(['Charles', 'Soyul', 'Hayoung', 'Charles', 'Hayoung', 'Soyul',
       'Soyul'],
      dtype='<U7')

In [21]:
data

array([[-0.30122259, -1.07766735,  0.72816649, -0.78461403],
       [ 1.21092064,  1.94872509,  1.48075477,  0.38494706],
       [-0.99819649, -2.82474341, -1.43895469,  0.05061005],
       [ 0.4086054 , -2.7141509 , -2.105519  ,  1.25500074],
       [-0.26437794,  0.44052697,  0.05397785,  0.26894058],
       [-0.46134929,  0.75876642,  0.69105776, -0.99149796],
       [ 1.17928241, -0.67011926, -1.60389774, -0.31038089]])

In [22]:
names == "Charles"

array([ True, False, False,  True, False, False, False], dtype=bool)

In [23]:
data[names=="Charles",:]

array([[-0.30122259, -1.07766735,  0.72816649, -0.78461403],
       [ 0.4086054 , -2.7141509 , -2.105519  ,  1.25500074]])

In [24]:
data[names=="Soyul",:]

array([[ 1.21092064,  1.94872509,  1.48075477,  0.38494706],
       [-0.46134929,  0.75876642,  0.69105776, -0.99149796],
       [ 1.17928241, -0.67011926, -1.60389774, -0.31038089]])

In [25]:
data[(names=="Charles") | (names=="Soyul"),:]

array([[-0.30122259, -1.07766735,  0.72816649, -0.78461403],
       [ 1.21092064,  1.94872509,  1.48075477,  0.38494706],
       [ 0.4086054 , -2.7141509 , -2.105519  ,  1.25500074],
       [-0.46134929,  0.75876642,  0.69105776, -0.99149796],
       [ 1.17928241, -0.67011926, -1.60389774, -0.31038089]])

In [26]:
data[:,3]

array([-0.78461403,  0.38494706,  0.05061005,  1.25500074,  0.26894058,
       -0.99149796, -0.31038089])

In [27]:
data[:,3] < 0

array([ True, False, False, False, False,  True,  True], dtype=bool)

In [28]:
data[data[:,3] < 0,:]

array([[-0.30122259, -1.07766735,  0.72816649, -0.78461403],
       [-0.46134929,  0.75876642,  0.69105776, -0.99149796],
       [ 1.17928241, -0.67011926, -1.60389774, -0.31038089]])

In [29]:
data[data[:,3] < 0,:] = 0

In [30]:
data[(data[:,2] < 0) | (names == "Charles"),:] 

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.99819649, -2.82474341, -1.43895469,  0.05061005],
       [ 0.4086054 , -2.7141509 , -2.105519  ,  1.25500074]])

In [31]:
data[(data[:,2] < 0) | (data[:,3] < 0),:] 

array([[-0.99819649, -2.82474341, -1.43895469,  0.05061005],
       [ 0.4086054 , -2.7141509 , -2.105519  ,  1.25500074]])

In [32]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.21092064,  1.94872509,  1.48075477,  0.38494706],
       [-0.99819649, -2.82474341, -1.43895469,  0.05061005],
       [ 0.4086054 , -2.7141509 , -2.105519  ,  1.25500074],
       [-0.26437794,  0.44052697,  0.05397785,  0.26894058],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [33]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.21092064,  1.94872509,  1.48075477,  0.38494706],
       [-0.99819649, -2.82474341, -1.43895469,  0.05061005],
       [ 0.4086054 , -2.7141509 , -2.105519  ,  1.25500074],
       [-0.26437794,  0.44052697,  0.05397785,  0.26894058],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [66]:
names2 = np.array(["자바","파이썬","스칼라","자바","코트린","파이썬","파이썬"])

In [67]:
names2 == '자바'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [68]:
names2 == "파이썬"

array([False,  True, False, False, False,  True,  True], dtype=bool)

In [69]:
data2 = np.random.randn(7,4)

In [70]:
data2

array([[ 0.6922126 ,  0.9998022 , -1.37550553,  0.18353103],
       [ 0.76767007,  1.63241274, -2.04345675,  0.80065015],
       [-0.40156544, -0.72356964,  0.42177611, -0.26261511],
       [ 0.92913869,  0.58311261, -1.94375394, -0.16977403],
       [-1.06843874,  0.40499856, -0.45639716, -0.25640787],
       [-0.35736508,  0.45307559,  0.13700435,  1.2574048 ],
       [-0.26749917,  1.08994961,  1.04214901,  0.2032401 ]])

In [72]:
data2[names2 == "파이썬",:]

array([[ 0.76767007,  1.63241274, -2.04345675,  0.80065015],
       [-0.35736508,  0.45307559,  0.13700435,  1.2574048 ],
       [-0.26749917,  1.08994961,  1.04214901,  0.2032401 ]])

In [73]:
data2[(names2=="파이썬") | (names2=="자바"),:]

array([[ 0.6922126 ,  0.9998022 , -1.37550553,  0.18353103],
       [ 0.76767007,  1.63241274, -2.04345675,  0.80065015],
       [ 0.92913869,  0.58311261, -1.94375394, -0.16977403],
       [-0.35736508,  0.45307559,  0.13700435,  1.2574048 ],
       [-0.26749917,  1.08994961,  1.04214901,  0.2032401 ]])

#3열의 데이터를 가져옴

In [74]:
data2[:,3]

array([ 0.18353103,  0.80065015, -0.26261511, -0.16977403, -0.25640787,
        1.2574048 ,  0.2032401 ])

#3열의 데이터 중에서 0 보다 작은 것은?

In [75]:
data2[:,3] < 0

array([False, False,  True,  True,  True, False, False], dtype=bool)

#3열의 데이터 중에서 0보다 작은 조건을 만족하는 행을 가져옴

In [76]:
data2[data2[:,3] < 0,:]

array([[-0.40156544, -0.72356964,  0.42177611, -0.26261511],
       [ 0.92913869,  0.58311261, -1.94375394, -0.16977403],
       [-1.06843874,  0.40499856, -0.45639716, -0.25640787]])

In [78]:
data2[data2[:,3] < 0,:] = 0

In [79]:
data2

array([[ 0.6922126 ,  0.9998022 , -1.37550553,  0.18353103],
       [ 0.76767007,  1.63241274, -2.04345675,  0.80065015],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.35736508,  0.45307559,  0.13700435,  1.2574048 ],
       [-0.26749917,  1.08994961,  1.04214901,  0.2032401 ]])

In [80]:
np.unique(names2)

array(['스칼라', '자바', '코트린', '파이썬'],
      dtype='<U3')