In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#sqrt : 제곱근
np.sqrt(arr)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ])

In [5]:
#LOG10은 10을 밑수로 하는 특정 수의 대수
np.log10(arr)

array([ 0.        ,  0.30103   ,  0.47712125,  0.60205999,  0.69897   ,
        0.77815125,  0.84509804,  0.90308999,  0.95424251])

In [6]:
x = np.random.randn(8)
y = np.random.randn(8)

In [7]:
x

array([-1.07216563,  0.46250896, -0.89675345, -0.62145223, -0.68422995,
        1.0623905 ,  0.30596317, -0.2548364 ])

In [8]:
y

array([ 0.43271274,  0.71181991, -0.01548054, -0.04378067,  0.52437206,
       -2.1335772 , -0.1112796 ,  0.28172228])

In [37]:
np.maximum(x,y)

array([ 0.43271274,  0.71181991, -0.01548054, -0.04378067,  0.52437206,
        1.0623905 ,  0.30596317,  0.28172228])

### 정수형 1차원 배열을 만들고, 다시 2차원으로 변환하고 더하기, 곱하기, sum() 계산해보기

In [49]:
x1 = np.arange(1,13).reshape(3,4)

In [50]:
x1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
x2 = np.arange(12,0,-1)

In [61]:
x2

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [65]:
x2 = x2.reshape(3,4)

In [66]:
x2

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [67]:
np.add(x1,x2)

array([[13, 13, 13, 13],
       [13, 13, 13, 13],
       [13, 13, 13, 13]])

In [68]:
np.multiply(x1,x2)

array([[12, 22, 30, 36],
       [40, 42, 42, 40],
       [36, 30, 22, 12]])

In [71]:
np.sum(x1)

78

In [74]:
x1.sum()

78

In [75]:
x1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
x1.sum(axis=0)

array([15, 18, 21, 24])

In [76]:
x1.sum(axis=1)

array([10, 26, 42])

In [98]:
np.mean(x1)

6.5

In [10]:
#여기서부터는 통계관련 함수 설명
arr = np.random.randn(5,4)

In [11]:
arr

array([[ -2.27353483e+00,   1.13473655e+00,  -2.05883784e-01,
          8.22752917e-01],
       [  1.20728450e+00,  -1.07828374e+00,  -1.81970981e-01,
         -1.81154830e-01],
       [  8.77157361e-01,  -2.24891763e-03,   7.42690529e-01,
         -2.70804580e-01],
       [  4.54688291e-02,   1.43679838e+00,   8.74630835e-01,
         -1.50198607e+00],
       [ -7.47287578e-01,   4.29790609e-01,  -1.77868282e-01,
          1.38301266e-02]])

In [12]:
arr.sum()

0.96411703496039569

In [13]:
arr.mean()

0.048205851748019786

In [14]:
#각 열(column) 별로 합계 구하기
arr.sum(axis=0)

array([-0.89091173,  1.92079288,  1.05159832, -1.11736244])

In [15]:
#각 행(row) 별로 합계 구하기
arr.sum(axis=1)

array([-0.52192915, -0.23412505,  1.34679439,  0.85491197, -0.48153512])

In [16]:
arr > 0

array([[False,  True, False,  True],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True,  True,  True, False],
       [False,  True, False,  True]], dtype=bool)

In [97]:
(arr > 0).sum()

8

### 정렬

In [78]:
#정렬 함수
arr = np.random.randn(8)

In [79]:
arr

array([-0.81650283,  0.14808001,  1.66910682,  0.45503798,  1.27138564,
        0.45195273, -0.93115647, -0.93589393])

In [80]:
#오름차순
np.sort(arr)

array([-0.93589393, -0.93115647, -0.81650283,  0.14808001,  0.45195273,
        0.45503798,  1.27138564,  1.66910682])

In [83]:
#내림차순
np.sort(arr)[::-1]

array([ 1.66910682,  1.27138564,  0.45503798,  0.45195273,  0.14808001,
       -0.81650283, -0.93115647, -0.93589393])

In [90]:
#2차원 배열 생성
arr = np.random.randn(5,3)

In [91]:
arr

array([[ 1.87857417,  0.42489316,  1.16587345],
       [ 2.17067668, -0.25498552,  0.21721869],
       [ 0.22506554, -0.44645007, -0.55354675],
       [-0.91852759, -0.59995032,  0.63054435],
       [-1.59173403, -0.52016744,  0.50669109]])

In [92]:
#행(row) 방향으로 sort 하기
np.sort(arr,axis=0)

array([[-1.59173403, -0.59995032, -0.55354675],
       [-0.91852759, -0.52016744,  0.21721869],
       [ 0.22506554, -0.44645007,  0.50669109],
       [ 1.87857417, -0.25498552,  0.63054435],
       [ 2.17067668,  0.42489316,  1.16587345]])

In [93]:
#열(column) 방향으로 sort 하기
np.sort(arr,axis=1)

array([[ 0.42489316,  1.16587345,  1.87857417],
       [-0.25498552,  0.21721869,  2.17067668],
       [-0.55354675, -0.44645007,  0.22506554],
       [-0.91852759, -0.59995032,  0.63054435],
       [-1.59173403, -0.52016744,  0.50669109]])

In [26]:
large_arr = np.random.randn(150)

In [27]:
large_arr

array([ -1.47069091e+00,   1.49240249e-01,   8.24010102e-01,
        -3.99638816e-01,  -4.93799170e-01,   1.19692320e+00,
         9.24120379e-01,   2.18306669e-01,  -1.17661103e+00,
         4.91116689e-01,   1.43737689e-01,  -1.13945940e+00,
         2.28875154e-01,  -5.45947874e-01,  -1.14698593e+00,
        -1.54775264e+00,   1.04859356e+00,   1.70208212e+00,
        -1.70843311e+00,  -1.30806804e+00,  -1.58053106e-01,
        -1.05568045e+00,   1.24705015e+00,   7.83706068e-01,
        -3.57655509e-01,   4.41957912e-01,   9.36583303e-01,
         1.09344585e+00,  -9.60620325e-01,  -3.59963256e+00,
        -6.49267323e-01,  -1.40433263e+00,  -2.21698129e-01,
        -5.57674606e-01,  -5.49476091e-02,   4.58565285e-01,
         2.94137085e-01,   3.80330512e-01,   4.15088831e-01,
        -1.25112054e-01,  -9.91024727e-01,   1.48876229e+00,
         1.32211174e-01,  -1.68034378e+00,  -8.46237812e-02,
        -1.43667479e-01,   3.67744428e-02,   5.49089560e-01,
         5.73112801e-01,

In [28]:
np.sort(large_arr)[::-1]

array([  2.55250157e+00,   1.70208212e+00,   1.62554800e+00,
         1.53959130e+00,   1.48876229e+00,   1.41510826e+00,
         1.30789715e+00,   1.24705015e+00,   1.22360255e+00,
         1.22277726e+00,   1.22029661e+00,   1.19692320e+00,
         1.18761188e+00,   1.13146718e+00,   1.12897765e+00,
         1.11558224e+00,   1.11113458e+00,   1.09344585e+00,
         1.06187165e+00,   1.05935526e+00,   1.05580496e+00,
         1.04859356e+00,   9.80445123e-01,   9.57570251e-01,
         9.36583303e-01,   9.24833235e-01,   9.24120379e-01,
         9.18453123e-01,   8.82871276e-01,   8.80154915e-01,
         8.79933992e-01,   8.56030503e-01,   8.28735561e-01,
         8.24010102e-01,   7.83706068e-01,   7.18411483e-01,
         6.71218224e-01,   5.90774695e-01,   5.73112801e-01,
         5.49089560e-01,   5.06916888e-01,   4.91116689e-01,
         4.75146012e-01,   4.58565285e-01,   4.51981819e-01,
         4.41957912e-01,   4.17873793e-01,   4.16015516e-01,
         4.15088831e-01,

In [29]:
#상위 5% 에 해당되는 값을 가져옴
np.sort(large_arr)[::-1][int(0.05 * len(large_arr))]

1.2470501534260892

In [96]:
names = np.array(["Charles","Soyul","Hayoung","Charles","Hayoung","Soyul","Soyul"])
ints = np.array([3,3,3,2,2,1,1,4,4])

In [31]:
#중복된 값을 제거함
np.unique(names)

array(['Charles', 'Hayoung', 'Soyul'],
      dtype='<U7')

In [32]:
np.unique(ints)

array([1, 2, 3, 4])

In [33]:
arr1 = np.random.randint(1,5,size=5)

In [34]:
arr1

array([4, 2, 1, 4, 3])

In [35]:
arr1.cumsum()

array([ 4,  6,  7, 11, 14], dtype=int32)

In [36]:
arr1.cumprod()

array([ 4,  8,  8, 32, 96], dtype=int32)